### ISSUE TITLE
User.update method doesn't modify the email

### ISSUE THREAD

**Issue by quantuminformation** [netlify/gotrue-js#65]
You can use the update method like this: https://gotruejs-playground.netlify.com/#update-user

But when I call this code from here: https://github.com/QuantumInformation/svelte-fullstack-starter/blob/master/src/stores/netlifyUserStore.js#L38

I get this error .then function is undefined

![image](https://user-images.githubusercontent.com/216566/70432544-6c61ca80-1a77-11ea-93d3-1b33bf5b16eb.png)

**Comment by QuantumInformation** [comment]
Turns out the then error was a mistake on my part, however when running update, the email is never changed

![image](https://user-images.githubusercontent.com/216566/70970735-13a5b980-2097-11ea-96a3-26f8689abc21.png)

As can be seen here after the .then is hit:  
![image](https://user-images.githubusercontent.com/216566/70970771-2b7d3d80-2097-11ea-82e1-018f328427fe.png)

**Comment by QuantumInformation** [comment]
If I log the updated user I see a prop called new_email set correctly, but its not reflected in the identity list. Am I to assume the original email never changes?

![image](https://user-images.githubusercontent.com/216566/70971465-ed811900-2098-11ea-99d1-6337cb2063c9.png)

**Comment by QuantumInformation** [comment]
I also found that if you update the email this way, you still have to log in with the old email if you log out

**Comment by QuantumInformation** [comment]
So are we to assume the user can never change their primary email? Seems very limiting for an auth system.

**Comment by clydemeng** [comment]
> So are we to assume the user can never change their primary email? Seems very limiting for an auth system.
Did we fix this issue?  Can the end users change their primary email?
